name: Deploy

on:
  push:
    branches:
    - master
    - 2021-update #temp

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
       fetch-depth: 0
    - name: build-image  # This should be a separate job. Image build only on Dockerfile change and include the package.json install then Push?
      run: make image
    - name: get-deps
      run: make get_deps
    - name: build-web
      run: make web_deploy
    - name: build-resume
      run: make resume_deploy
    - name: move files
      run: mkdir public && mv index.html public/index.html && mv resume.pdf public/resume.pdf && mv img/ public/img/
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'ap-southeast-2'   # optional: defaults to us-east-1
        SOURCE_DIR: 'public'      # optional: defaults to entire repository
    # Invalidate Cloudfront (this action)
    - name: invalidate_cloudfront
      uses: chetan/invalidate-cloudfront-action@master
      env:
        DISTRIBUTION: ${{ secrets.CLOUDFRONT_DISTRIBUTION }}
        PATHS: '/index.html /resume.pdf'
        AWS_REGION: 'ap-southeast-2'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}